---
title: "git_01"
author: "Caina S Guardado"
date: "09/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Man Naturally loves delay,    
And to procrastinate;    
Business put off from day to day    
Is always done too late.    

Let every hour be in its place    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I have been one acquainted with the night.    
I have walked out in rain—and back in rain.     
I have outwalked the furthest city light.    

I have looked down the saddest city lane.    
I have passed by the watchman on his beat     

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,    
      Shining with all his might:    
He did his very best to make    
      The billows smooth and bright    
And this was odd, because it was    
      The middle of the night.    

The moon was shining sulkily,    
      Because she thought the sun    
Had got no business to be there      
      After the day was done —    
"It's very rude of him," she said,    
      "To come and spoil the fun."    
      

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

I see you peeking timidly    
from between the skeletal bars    
of your bleached, bony fortress,    
vibrant colors a sign of defiance    
in this scorched grayscape.    
I hear your silent exclamation     
of resurgence and rebirth.  

Your seed burrowed deep    
as the buck sheltered you    
from the raging furnace above.    
He must have been fearless,    
offering himself as sanctuary     
to your unborn, fragile beauty    
in the face of nature’s fury.    
